#!/bin/sh

# Fix for w10
if [ -t 1 ]; then
  exec < /dev/tty
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs v fmt -w

# Add back the modified files to staging
echo "$FILES" | xargs git add

exit 0